import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import NavbarAdmin from "@/components/admin/NavbarAdmin";
import { Toaster } from 'sonner'

import Providers from "@/components/Provaiders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moonlight ",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Providers>
         <SidebarProvider>
       <NavbarAdmin />
        {children}
         <Toaster
          position="top-center"
          toastOptions={{
            style: {
              background: 'var(--color-lavender)',
              color: 'var(--color-dark-gray)',
              border: '1px solid var(--color-purple)',
            },
          }}
        />
        </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
